pre-commit:
  scripts:
    'hello.js':
      runner: node
  commands:
    🎨 format:
      glob: '*.{js,ts,jsx,tsx,css,json,md}'
      run: npx prettier --write {staged_files}
    🧹 lint:
      glob: '*.{js,ts,jsx,tsx}'
      run: npx eslint {staged_files} --fix --cache --cache-location=./.next/cache/eslint/.standalone-cache &&npx eslint {staged_files} --cache --cache-location=./.next/cache/eslint/.standalone-cache
# prepare-commit-msg:
#   commands:
#     📝 commitlint:
#       run: npx commitlint --edit $1
